“Building Your Healthcare Team with a focus on Alzheimer’s and Dementia”

The event that Human Health Project is hosting on November 12 at 10:00 am Pacific Time/1:00 pm Eastern Time, “Building Your Healthcare Team,” will be significant in that this event is a live panel with a special focus on Alzheimer’s disease and dementia. 

In advance of this event, it is important to note that having a strong healthcare team to help cope with diseases such as Alzheimer’s and dementia is crucial. As stated by Sydney Thomas, Public Policy Coordinator for the Alzheimer’s Association, North Central and West Texas chapters, “A care team is the group of people who you’ll partner with and rely on to provide you help, care, support and connection throughout the course of the disease. You are in the center, but you are not there alone. Developing your own network of helpers can help you lead a more productive, active and engaged life while living with the disease.” Ms. Thomas’s quote is ultimately indicative of the lasting impact that having a healthcare team can have for an individual.

In addition, as referred to by the Alzheimer’s Association, a person can start building one’s healthcare team by selecting a decision-maker that he or she trusts. As stated by the Alzheimer’s Association, a decision-maker is often a family member or friend who is selected to build a healthcare team for another person. As stated by the global healthcare and insurance company, Cigna, in the article, “Choosing a Healthcare Agent,” a decision-maker can also be a healthcare proxy, who is a person that is chosen in advance to make healthcare decisions for an individual. This is done in the event that the particular individual in need becomes unable to do so, or feels that it is in their best interest to have a healthcare proxy. This can be especially important for an individual who is seeking to build their healthcare team when experiencing serious diseases such as Alzheimer’s and dementia.

In addition, as further discussed in the aforementioned article by Cigna, state laws differ in regards to the types of decisions healthcare proxies can make. In general, as stated by Cigna, a healthcare proxy can agree to or decline treatment for an individual. Ultimately, as mentioned by the Alzheimer’s Association, it is important for an individual seeking to build their healthcare team to have a conversation with the decision-maker, who often would be identified as the healthcare proxy. This dialogue would be in regards to the type of help that is needed, as well as regarding long-term goals. Ultimately, as referenced by the Alzheimer’s Association, the help provided by advocates regarding healthcare matters is significant, as it can be helpful in decreasing high stress levels to individuals in need of assistance.

Building one’s healthcare team is also especially important for diseases such as Alzheimer’s and dementia. With regards to Alzheimer’s disease, The Cleveland Clinic defines Alzheimer’s disease as “a progressive and fatal disease in which nerve cells in the brain degenerate and brain matter shrinks, resulting in impaired thinking, behavior and memory.” With regards to dementia, according to the Mayo Clinic, common symptoms of dementia include memory loss, difficulty in performing tasks, difficulties with communication, and personality changes. According to the Mayo Clinic, in addition to cognitive symptoms, many types of dementia also include physical symptoms. These include the erratic eye movements of Huntington’s disease or the tremors linked to Parkinson’s disease.

Ultimately, the severity of both Alzheimer’s disease and dementia makes it all the more important to have an effective healthcare team to help one cope with these diseases. In doing so, an individual living with Alzheimer’s and dementia who is able to have an effective healthcare team, despite the presence of disease, can lead a healthier and fulfilling life.